spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "MyHome"
  datasource:
    url: "jdbc:postgresql://localhost:5432/myhome"
    driver-class-name: "org.postgresql.Driver"
    username: "postgres"
    password: "demo"
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQL9Dialect"
    hibernate:
      ddl-auto: "update"
    show-sql: true
